/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ['class'],
    content: [
        './pages/**/*.{ts,tsx}',
        './components/**/*.{ts,tsx}',
        './app/**/*.{ts,tsx}',
        './src/**/*.{js,jsx,ts,tsx}',
    ],
    prefix: '',
    theme: {
        container: {
            center: true,
            padding: '2rem',
            screens: {
                '2xl': '1400px',
            },
        },
        colors: {
            primary: '#0F4C81',
            text: {
                DEFAULT: '#000000',
                'dark': '#FFFFFF',
            },
            secondary: '#F2F2F2',
            white: '#FFFFFF',
            black: '#000000',
            blue: {
                100: '#5865F2',
                200: '#404EED',
                300: '#05A8FC',
                400: '#4752C4',
                pastel: '#E1E8FF',
                dark: '#3B4A6B',
                darkest: '#2D3A54',
            },
            gray: {
                75: '#1E1F22',
                100: '#F6F6F6',
                125: '#949BA4',
                150: '#B5B8BB',
                151: '#5C5E66',
                175: '#6D6F78',
                200: '#99AAB5',
                250: '#4E5058',
                251: '#EBEDEF',
                300: '#313338',
                350: '#36373D',
                351: '#E0E1E5',
                375: '#383A40',
                376: '#EBEDEF',
                400: '#23272A',
                450: '#404249',
                451: '#D7D9DC',
                500: '#BDBDBD',
                600: '#2B2D31',
                601: '#E3E5E8',
                'sidebar-light': '#F2F3F5',
                700: '#1F2023',
                'spoiler-light': '#C4C9CD',
                'border': '#1E1F22',
            },
            yellow: {
                500: '#EAB308',
                'hl-body': '#444039',
                'hl-mark': '#EFB132',
                'hl-body-light': '#FDF7EC',
            },
            orange: {
                500: '#F97316',
            },
            cyan: {
                400: '#22D3EE',
            },
            purple: {
                500: '#A855F7',
                700: '#7C3AED',
            },
            red: {
                400: '#F54343',
                500: '#EF4444',
                600: 'red',
                pastel: '#F8D7DA',
                dark: '#6B3A3A',
                darkest: '#542D2D',
            },
            green: {
                pastel: '#D4EDDA',
                400: '#96F04A',
                '400-light': '#187902',
                500: '#22C55E',
                '600': '#35E717',
                700: '#15803D',
                800: '#166534',
            },
        },
        fontFamily: {
            sans: ['Inter', 'sans-serif'],
            serif: ['Inter', 'sans-serif'],
            mono: ['Roboto Mono', 'sans-serif'],
        },
        extend: {
            colors: {
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
            keyframes: {
                'accordion-down': {
                    from: { height: '0' },
                    to: { height: 'var(--radix-accordion-content-height)' },
                },
                'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to: { height: '0' },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
            },
        },
    },
    plugins: [require('tailwindcss-animate')],
    safelist: [
        'border',
        'border-solid',
        'border-gray-border',
        'ml-14',
        'mr-14',
        'p-2',
        'm-1',
        'p-5.5',
        'm-2',
        'w-[400px]',
        'h-[300px]',
        'text-sm',
        'bg-blue-100',
        'hover:bg-blue-400',
        'text-sm',
        'text-white',
        'font-bold',
        'py-2',
        'px-4',
        'rounded',
        'whitespace-pre-wrap',
        'bg-gray-700',
        'text-gray-700',
        'hover:text-white',
        'text-green-400',
        'px-3',
        'py-1',
        'text-red-600',
    ],
};
